### ISSUE TITLE
ProductReservationView throws attribute error, object has no attribute 'instance' 

### ISSUE THREAD

**Issue by dylanjw** [luisza/djreservation#7]
https://github.com/luisza/djreservation/blob/9ebb7fc8080c8ee21008fb7771b77cc9d24c722a/djreservation/views.py#L200

Why is `self.instance` referenced throughout this view?  Shouldnt it be a reference to the model instance, not the view?

Is this a bug or am I missing something?

**Comment by luisza** [comment]
That is because self.instance is set before post, take a look here https://github.com/luisza/djreservation/blob/9ebb7fc8080c8ee21008fb7771b77cc9d24c722a/djreservation/views.py#L251

**Comment by luisza** [comment]
your Urls needs to look like this 

urlpatterns = [
        ...
        url(r"^reservationroom/create/(?<pk>\d+)$", RoomReservation.as_view())
]

**Comment by dylanjw** [comment]
Thank you!
